/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as BoekenRouteImport } from './routes/boeken'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as GalerijRouteImport } from './routes/galerij'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as PrivacybeleidRouteImport } from './routes/privacybeleid'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBoekingenRouteImport } from './routes/admin/boekingen'
import { Route as AdminDienstenRouteImport } from './routes/admin/diensten'
import { Route as AdminInstellingenRouteImport } from './routes/admin/instellingen'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BoekenIndexRouteImport } from './routes/boeken.index'
import { Route as BoekenBevestigdRouteImport } from './routes/boeken.bevestigd'
import { Route as BoekingAnnulerenBookingIdRouteImport } from './routes/boeking/annuleren/$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekenRoute = BoekenRouteImport.update({
  id: '/boeken',
  path: '/boeken',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerijRoute = GalerijRouteImport.update({
  id: '/galerij',
  path: '/galerij',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacybeleidRoute = PrivacybeleidRouteImport.update({
  id: '/privacybeleid',
  path: '/privacybeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBoekingenRoute = AdminBoekingenRouteImport.update({
  id: '/boekingen',
  path: '/boekingen',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDienstenRoute = AdminDienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstellingenRoute = AdminInstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BoekenIndexRoute = BoekenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoekenRoute,
} as any)
const BoekenBevestigdRoute = BoekenBevestigdRouteImport.update({
  id: '/bevestigd',
  path: '/bevestigd',
  getParentRoute: () => BoekenRoute,
} as any)
const BoekingAnnulerenBookingIdRoute =
  BoekingAnnulerenBookingIdRouteImport.update({
    id: '/boeking/annuleren/$bookingId',
    path: '/boeking/annuleren/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/boeken': typeof BoekenRouteWithChildren
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/galerij': typeof GalerijRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/admin/boekingen': typeof AdminBoekingenRoute
  '/admin/diensten': typeof AdminDienstenRoute
  '/admin/instellingen': typeof AdminInstellingenRoute
  '/admin/login': typeof AdminLoginRoute
  '/boeken/bevestigd': typeof BoekenBevestigdRoute
  '/admin/': typeof AdminIndexRoute
  '/boeken/': typeof BoekenIndexRoute
  '/boeking/annuleren/$bookingId': typeof BoekingAnnulerenBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/galerij': typeof GalerijRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/admin/boekingen': typeof AdminBoekingenRoute
  '/admin/diensten': typeof AdminDienstenRoute
  '/admin/instellingen': typeof AdminInstellingenRoute
  '/admin/login': typeof AdminLoginRoute
  '/boeken/bevestigd': typeof BoekenBevestigdRoute
  '/admin': typeof AdminIndexRoute
  '/boeken': typeof BoekenIndexRoute
  '/boeking/annuleren/$bookingId': typeof BoekingAnnulerenBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/boeken': typeof BoekenRouteWithChildren
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/galerij': typeof GalerijRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/admin/boekingen': typeof AdminBoekingenRoute
  '/admin/diensten': typeof AdminDienstenRoute
  '/admin/instellingen': typeof AdminInstellingenRoute
  '/admin/login': typeof AdminLoginRoute
  '/boeken/bevestigd': typeof BoekenBevestigdRoute
  '/admin/': typeof AdminIndexRoute
  '/boeken/': typeof BoekenIndexRoute
  '/boeking/annuleren/$bookingId': typeof BoekingAnnulerenBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/algemene-voorwaarden'
    | '/boeken'
    | '/contact'
    | '/diensten'
    | '/galerij'
    | '/over-ons'
    | '/privacybeleid'
    | '/admin/boekingen'
    | '/admin/diensten'
    | '/admin/instellingen'
    | '/admin/login'
    | '/boeken/bevestigd'
    | '/admin/'
    | '/boeken/'
    | '/boeking/annuleren/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemene-voorwaarden'
    | '/contact'
    | '/diensten'
    | '/galerij'
    | '/over-ons'
    | '/privacybeleid'
    | '/admin/boekingen'
    | '/admin/diensten'
    | '/admin/instellingen'
    | '/admin/login'
    | '/boeken/bevestigd'
    | '/admin'
    | '/boeken'
    | '/boeking/annuleren/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/algemene-voorwaarden'
    | '/boeken'
    | '/contact'
    | '/diensten'
    | '/galerij'
    | '/over-ons'
    | '/privacybeleid'
    | '/admin/boekingen'
    | '/admin/diensten'
    | '/admin/instellingen'
    | '/admin/login'
    | '/boeken/bevestigd'
    | '/admin/'
    | '/boeken/'
    | '/boeking/annuleren/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  BoekenRoute: typeof BoekenRouteWithChildren
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  GalerijRoute: typeof GalerijRoute
  OverOnsRoute: typeof OverOnsRoute
  PrivacybeleidRoute: typeof PrivacybeleidRoute
  BoekingAnnulerenBookingIdRoute: typeof BoekingAnnulerenBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boeken': {
      id: '/boeken'
      path: '/boeken'
      fullPath: '/boeken'
      preLoaderRoute: typeof BoekenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerij': {
      id: '/galerij'
      path: '/galerij'
      fullPath: '/galerij'
      preLoaderRoute: typeof GalerijRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacybeleid': {
      id: '/privacybeleid'
      path: '/privacybeleid'
      fullPath: '/privacybeleid'
      preLoaderRoute: typeof PrivacybeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/boekingen': {
      id: '/admin/boekingen'
      path: '/boekingen'
      fullPath: '/admin/boekingen'
      preLoaderRoute: typeof AdminBoekingenRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/diensten': {
      id: '/admin/diensten'
      path: '/diensten'
      fullPath: '/admin/diensten'
      preLoaderRoute: typeof AdminDienstenRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/instellingen': {
      id: '/admin/instellingen'
      path: '/instellingen'
      fullPath: '/admin/instellingen'
      preLoaderRoute: typeof AdminInstellingenRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/boeken/': {
      id: '/boeken/'
      path: '/'
      fullPath: '/boeken/'
      preLoaderRoute: typeof BoekenIndexRouteImport
      parentRoute: typeof BoekenRoute
    }
    '/boeken/bevestigd': {
      id: '/boeken/bevestigd'
      path: '/bevestigd'
      fullPath: '/boeken/bevestigd'
      preLoaderRoute: typeof BoekenBevestigdRouteImport
      parentRoute: typeof BoekenRoute
    }
    '/boeking/annuleren/$bookingId': {
      id: '/boeking/annuleren/$bookingId'
      path: '/boeking/annuleren/$bookingId'
      fullPath: '/boeking/annuleren/$bookingId'
      preLoaderRoute: typeof BoekingAnnulerenBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBoekingenRoute: typeof AdminBoekingenRoute
  AdminDienstenRoute: typeof AdminDienstenRoute
  AdminInstellingenRoute: typeof AdminInstellingenRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBoekingenRoute: AdminBoekingenRoute,
  AdminDienstenRoute: AdminDienstenRoute,
  AdminInstellingenRoute: AdminInstellingenRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BoekenRouteChildren {
  BoekenBevestigdRoute: typeof BoekenBevestigdRoute
  BoekenIndexRoute: typeof BoekenIndexRoute
}

const BoekenRouteChildren: BoekenRouteChildren = {
  BoekenBevestigdRoute: BoekenBevestigdRoute,
  BoekenIndexRoute: BoekenIndexRoute,
}

const BoekenRouteWithChildren =
  BoekenRoute._addFileChildren(BoekenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  BoekenRoute: BoekenRouteWithChildren,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  GalerijRoute: GalerijRoute,
  OverOnsRoute: OverOnsRoute,
  PrivacybeleidRoute: PrivacybeleidRoute,
  BoekingAnnulerenBookingIdRoute: BoekingAnnulerenBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
